config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :purchasers, only: [:index,:create]
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :users, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ }
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヴー]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヴー]+\z/ }
  validates :birthday, presence: true
  pattern = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,}+\z/i
  validates :password, format: { with: pattern }

  has_many :items
  has_many :purchasers
  has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user =  User.find(params[:id])
    @items = @user.items.order('created_at DESC')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/second-header"%>

  <div class='item-contents'>
    <div class="subtitle" >
      <%=@user.nickname%>の商品一覧
    </div>

     <div id="star-rate<%= @user.id %>">
       <h2 class="rank">総合評価（<%= @user.items.joins(:comments).average(:rate).to_f.round(1) %>点）</h2>
     </div> 
       <script>
        $('#star-rate<%= @user.id%>').raty({
         size      : 36,
         starOff   : '<%= asset_path('star-off.png') %>',
         starOn    : '<%= asset_path('star-on.png') %>',
         starHalf: '<%= asset_path('star-half.png') %>',
         half: true,
         readOnly: true, 
         score: <%= @user.items.joins(:comments).average(:rate).to_f.round(1) %>,
        });
       </script>

    <ul class='item-lists'>

      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id),method: :get do %>
        <div class='item-img-content' >
          <%= image_tag item.image, class: "item-img" if item.image.attached?%>

          <% if item.purchaser != nil %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.product_name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.charge.name %></span>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>

      <% if @items.blank? %>
      <li class='list'>
        <%= image_tag "circle-9.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            出品商品はありません。
          </h3>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

<%= render "shared/second-footer"%>